export const cursos = [
    /** -----------INFORMATORIO: ETAPA2------------ */
    {
        titulo: 'Base de datos',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Informatorio: Etapa 2',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Programación web',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Informatorio: Etapa 2',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Variedades',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Informatorio: Etapa 2',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    /** -----------EMPLEO Y EMPRENDIMIENTOS------------ */
    {
        titulo: 'Gestión de redes sociales',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Formalización de emprendimientos',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Diseño Gráfico',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Herramientras para el empleo',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Administración de emprendimientos',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Edición de videos para emprendimientos',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Introducición al desarrollo de videojuegos',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Vender online',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Manipulación higiénica de alimentos',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Excel inicial',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Excel Avanzado',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Word inicial',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Word inicial',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Empleo y Emprendimientos',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    /** -----------INFORMATORIO------------ */
    {
        titulo: 'Talleres para emprender en Tics',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Informatorio',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Especialización en tecnologías de desarrollo',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Informatorio',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Programación y desarrollo web',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Informatorio',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
    {
        titulo: 'Introducción a la Programación',
        descripcion: 'Lorem ipsum dolor sit, consectetur adipiscing elit.',
        categoria: 'Informatorio',
        imgUrl: 'pro-pic t4 ',
        UrlToRedirect: '',
    },
]

